In [18]:
import time
liste = [11,22,33,44,55,66,77,88,99,11] * 5000000
yeniListe = []
start = time.time()
for x in liste:
    yeniListe.append(x*x)
print(yeniListe[0:5])
end = time.time()
print(end-start)

[121, 484, 1089, 1936, 3025]
4.909419059753418


In [19]:
import numpy as np

numpyArr = np.array(liste)
start = time.time()
newArr = numpyArr * numpyArr
end = time.time()
print(end-start)

0.14792776107788086


In [21]:
liste = [11,22,33,44,55,66,77,88,99,11]

npArr = np.array(liste)
npArr2 = npArr*2
print(npArr2)

[ 22  44  66  88 110 132 154 176 198  22]


In [27]:
arr = np.arange(1,101)
m = arr.reshape(10,10)
print(m)

identityM = np.eye(10)
print(identityM)

print(np.matmul(m,identityM))

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
[[  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.]
 [ 11.  12.  13.  14.  15.  16.  17.  18.  19.  20.]
 [ 21.  22.  23.  24.  25.  26.  27.  28.  29.  30.]
 [ 31.  32.  33.  34.  35.  36.  37.  38.  39.  40.]
 [ 41.  42.  43.  44.  45.

In [29]:
a = np.ones(10)
a.append(88)
print(a)

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [30]:
a = np.ones(10)
print(b)

[3. 3. 3. 3. 3. 3. 3. 3. 3. 3.]


In [35]:
a = np.array([1,2,3,4,5])
b = np.array([1,1])

c = a * b
print(c)

ValueError: operands could not be broadcast together with shapes (5,) (2,) 

In [47]:
g = np.loadtxt("data.txt",dtype=str,delimiter=',')
print(g)
print(g[1:])


b = np.array(g[1:],dtype=int)
print(b)

[['x' 'y' 'z' 'sonuc']
 ['1' '1' '1' '6']
 ['2' '1' '3' '11']
 ['0' '1' '4' '6']
 ['4' '5' '1' '23']
 ['2' '5' '9' '25']]
[['1' '1' '1' '6']
 ['2' '1' '3' '11']
 ['0' '1' '4' '6']
 ['4' '5' '1' '23']
 ['2' '5' '9' '25']]
[[ 1  1  1  6]
 [ 2  1  3 11]
 [ 0  1  4  6]
 [ 4  5  1 23]
 [ 2  5  9 25]]


In [57]:
import pandas as pd

data = pd.read_excel("class.xlsx")

data.loc[6] = [123,"Ali","Desidero"]

data.to_excel("test.xlsx",index=False)